@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam class {
    FontColor UI_TEXT_DARK
}
skinparam class<<Hidden>> {
    FontColor white
    BackgroundColor white
}

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class StatusBarFooter
Class CommandBox

Class TabSection
Class ListSection
Class StudentDetailsTab
Class DashboardTab
Class FilterPanel
Class DemeritListTab
}

package Model <<Rectangle>> {
Class HiddenModel <<Hidden>>
}

package Logic <<Rectangle>> {
Class HiddenLogic <<Hidden>>
}

Class HiddenOutside <<Hidden>>
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow

MainWindow -down-> "0..1" HelpWindow
MainWindow -down-> "1" CommandBox
MainWindow -down-> "1" ResultDisplay
MainWindow -down-> "1" TabSection
MainWindow -down-> "1" ListSection
MainWindow -down-> "1" StatusBarFooter

TabSection -down-> "1" StudentDetailsTab
TabSection -down-> "1" DashboardTab
TabSection -down-> "1" DemeritListTab

ListSection --> "1" FilterPanel
ListSection --> "1" PersonListPanel

PersonListPanel -down-> "*" PersonCard

PersonCard --|> UiPart
DemeritListTab --|> UiPart
DashboardTab --|> UiPart
StudentDetailsTab --|> UiPart
CommandBox --|> UiPart
TabSection --|> UiPart
ListSection --|> UiPart
StatusBarFooter --|> UiPart
ResultDisplay --|> UiPart
HelpWindow --|> UiPart
PersonListPanel --|> UiPart
FilterPanel --|> UiPart
MainWindow --|> UiPart

PersonCard .down.> Model
FilterPanel .down.> Model

UiManager -right-> Logic
MainWindow -left-> Logic

CommandBox -[hidden]right- TabSection
ListSection -[hidden]right- StatusBarFooter
TabSection -[hidden]right- CommandBox
ResultDisplay -[hidden]right- ListSection
UiPart -[hidden]down- Model
TabSection -[hidden]right- ResultDisplay
DashboardTab -[hidden]right- DemeritListTab
DemeritListTab -[hidden]right- StudentDetailsTab

MainWindow -[hidden]-|> UiPart
@enduml
